#######################################################################
# Dockerfile to build Redis container image
# Based on redis official repository image
#######################################################################
FROM redis:3.2
MAINTAINER Rogério Peixoto (rcbpeixoto@gmail.com)
