#######################################################################
# Dockerfile to build Selenium grid container image
# Based on docker-selenium official repository
#######################################################################
FROM elgalu/selenium:2.53.0o
MAINTAINER Rogério Peixoto (rcbpeixoto@gmail.com)
