#######################################################################
# Dockerfile to build Redis container image
# Based on redis alpine official repository 20mb image
#######################################################################
FROM redis:3.2.0-alpine
MAINTAINER Rogério Peixoto (rcbpeixoto@gmail.com)
